// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CheckUpdate():Promise<string>;

export function LoadCatalogue():Promise<Array<main.SwitchTitle>>;

export function LoadLocalGames():Promise<void>;

export function OrganizeLibrary():Promise<void>;

export function RequestStartupProgress():Promise<void>;

export function Rescan(arg1:boolean):Promise<void>;
