// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function LoadCatalog() {
  return window['go']['main']['App']['LoadCatalog']();
}

export function RequestStartupProgress() {
  return window['go']['main']['App']['RequestStartupProgress']();
}
