// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function LoadCatalog(arg1) {
  return window['go']['main']['App']['LoadCatalog'](arg1);
}

export function RequestStartupProgress() {
  return window['go']['main']['App']['RequestStartupProgress']();
}
