// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckUpdate() {
  return window['go']['main']['App']['CheckUpdate']();
}

export function LoadCatalogue() {
  return window['go']['main']['App']['LoadCatalogue']();
}

export function LoadLocalGames() {
  return window['go']['main']['App']['LoadLocalGames']();
}

export function OrganizeLibrary() {
  return window['go']['main']['App']['OrganizeLibrary']();
}

export function RequestStartupProgress() {
  return window['go']['main']['App']['RequestStartupProgress']();
}

export function Rescan(arg1) {
  return window['go']['main']['App']['Rescan'](arg1);
}
