// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function LoadCatalog(arg1:main.CatalogFilters):Promise<main.CatalogPage>;

export function LoadLibraryFiles():Promise<Array<main.LibraryFileEntry>>;

export function LoadLibraryGames():Promise<Array<main.LibrarySwitchGame>>;

export function RequestStartupProgress():Promise<void>;
